#
# Makefile for the Goodix gt9xx touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_GT9XX_v28)		+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_UPDATE_v28)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_DEBUG_v28)	+= goodix_tool.o
